version: '3.9'

services:
  database:
    image: postgres
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    networks:
      - network
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: $DATABASE_NAME
    ports:
      - $DATABASE_PORT:5432

  adminer:
    image: adminer
    restart: always
    networks:
      - network
    environment:
      ADMINER_DEFAULT_SERVER: database
    ports:
      - $ADMINER_PORT:8080

networks:
  network:
    driver: bridge
